POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Sai",
    "email": "sai@gmail.com",
    "password": "Sai@2025"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "roman@gmail.com",
    "password": "Roman@2025"
}
###

GET http://localhost:4000/added-products-list
###